### ISSUE TITLE
Fix no-overlap test

### ISSUE THREAD

**Issue by orthecreedence** [orthecreedence/cl-async#122]
It's failing in linux, and pretty much renders cl-async useless for TCP communication. Need to figure out when this happened, although the last time it tested successfully was many, many commits ago.

**Comment by ivan4th** [comment]
Strange, it doesn't fail on my machine. Does `*buffer-writes*` affect it?

**Comment by orthecreedence** [comment]
Nope, that was my first guess. I dug in a bit last night and it looks like it's some kind of test timeout issue, not that the data is actually "crossing streams." So maybe the content mixing *is* a drakma-async bug, or maybe it's still a cl-async bug in a different place. Need to keep digging!

**Comment by nightshade427** [comment]
Let me know if there is anything I can do to help. This is a major blocker for me and Im glad to help in any way I can :)

**Comment by orthecreedence** [comment]
Have you noticed this with any other projects or just drakma-async? Also, any test case you can give me would be really helpful.

**Comment by nightshade427** [comment]
Sure I will try exact same work flow with carrier and see. I use drakma async with cl-async and doesn't have the issue though. If carrier shows the same issue I will I try and get a simple repo case for you.

**Comment by nightshade427** [comment]
Sorry the delay, going to try with carrier today and repo with it. :)

**Comment by nightshade427** [comment]
yeah I replaced drakma-async with carrier call and it does same thing.

**Comment by nightshade427** [comment]
Let me know if I can help in any way :)

**Comment by nightshade427** [comment]
I'll try and see what I can track down as well

**Comment by nightshade427** [comment]
Actually upon tracking this down more. It looks like it might be wookie when its sending the responses that is causing the mixing. Which would also explain why it happens with drakam and carrier.

**Comment by nightshade427** [comment]
Still tracking down though, will keep you posted.

**Comment by nightshade427** [comment]
Yeah it is definitely wookie reponse handling. I took and original js file from webserver, and proxied it though wookie using drakma, and took that result right before calling send-response and output it to file, and diffed the proxied file with original and there was zero, then I took what wookie gave me in the browser and it was different, its like the js file got scrambled up a little.

**Comment by nightshade427** [comment]
If I refresh really quickly I also get this now when I didnt on previous libevent wookie and cl-async.

```lisp
The function COMMON-LISP:T is undefined.                                                                                
   [Condition of type UNDEFINED-FUNCTION]                                                                               
                                                                                                                        
Restarts:                                                                                                               
 0: [CONTINUE-EVENT-LOOP] Continue the event loop, passing the error to the default handler.                            
 1: [ABORT-CALLBACK] Abort cl-async callback.                                                                           
 2: [*EXIT-EVENT-LOOP] Exit the current event loop.                                                                     
 3: [RETRY] Retry SLIME REPL evaluation request.                                                                        
 4: [ABORT] Return to SLIME's top level.                                                                                
 5: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {100A888033}>)                                                 
                                                                                                                        
Backtrace:                                                                                                              
  0: (SB-KERNEL:%COERCE-CALLABLE-TO-FUN T)                                                                              
  1: ((LABELS #:CONTINUE-FN59 :IN CL-ASYNC::TIMER-CB) #<CL-ASYNC:STREAMISH-CLOSED {100B713BE3}>)                        
  2: ((FLET #:HANDLER72 :IN CL-ASYNC::TIMER-CB) #<CL-ASYNC:STREAMISH-CLOSED {100B713BE3}>)                              
  3: (SIGNAL #<CL-ASYNC:STREAMISH-CLOSED {100B713BE3}>)                                                                 
  4: (ERROR CL-ASYNC:SOCKET-CLOSED :CODE -1 :MSG "Trying to operate on a closed socket" :SOCKET #<CL-ASYNC:TCP-SOCKET {$
  5: (WOOKIE:SEND-RESPONSE #<WOOKIE:RESPONSE {100B6B9F23}> :STATUS 500 :HEADERS NIL :BODY "There was an error processin$
  6: (WOOKIE::MAIN-EVENT-HANDLER #<CL-ASYNC:SOCKET-RESET {100B70ED83}> #<CL-ASYNC:TCP-SOCKET {10076D17E3}> NIL)         
  7: ((LAMBDA NIL :IN CL-ASYNC::TIMER-CB))                                                                              
  8: (CL-ASYNC-UTIL:CALL-WITH-CALLBACK-RESTARTS #<CLOSURE (LAMBDA NIL :IN CL-ASYNC::TIMER-CB) {100B7104EB}> :CONTINUE-F$
  9: (CL-ASYNC::TIMER-CB #.(SB-SYS:INT-SAP #X7FFFCC03E820))                                                             
 10: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/root/.cache/common-lisp/sbcl-1.2.8-linux$
 11: ("foreign function: call_into_lisp")                                                                               
 12: ("foreign function: funcall3")                                                                                     
 13: ("foreign function: #x20100D6B")                                                                                   
 14: ("foreign function: #x2024F73928")                                                                                 
 15: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SERVER:RUN) #<NULL-LEXENV>)                                                         
 16: (EVAL (SERVER:RUN))                                                                                                
 17: (SWANK::EVAL-REGION "(server:run) ..)
```

**Comment by nightshade427** [comment]
I should also mention it doesn do this ever time either. Sometimes the file comes across fine, Other times it does now.

**Comment by nightshade427** [comment]
I also get this when hitting wookie with a route that doesnt exist.

```lisp
<WARN> [22:25:14] wookie - (route) Missing route: NIL                                                                 
 <ERROR> [22:25:14] wookie - (hook) Error running hooks (socket #<TCP-SOCKET                                            
                                                                  {100B1F2023}>): attempt to RETURN-FROM a block or GO \
to a tag that no longer exists 
```

**Comment by nightshade427** [comment]
Are the sockets reused? I added some metadata to socket class and set it on socket instances only when a certain resource was asked for. But strangly I see the meta data show up 4-5 connections down the line and way before it is even possible to set it. Its like that socket got reused for another request coming in?

**Comment by nightshade427** [comment]
Okay so far I have tracked the data down to this point and data is all good till it gets here (write-to-uvstream). Based on the above two files (the origial and the one retrieved from wookie), where it looked like part of the output was overwriten part another part of the output. I think it has something to do with this function and and its interaction with do-chunk-data helper. Still tracking it down more. But, at this point in the stack all data looks correct (md5 matches).

https://github.com/orthecreedence/cl-async/blob/master/src/streamish.lisp#L138
https://github.com/orthecreedence/cl-async/blob/master/src/util/helpers.lisp#L34

**Comment by nightshade427** [comment]
Im using libuv 1.0.0 should I maybe be using diff version?

**Comment by nightshade427** [comment]
Same using latest libuv 1.4.0

**Comment by nightshade427** [comment]
will investigate from write-to-uvstream and down tomorrow

**Comment by nightshade427** [comment]
Okay it looks good from here too at thne write-to-uvstream, if I take the buffer-c and concate the results its md5 matches the original content. So it must be even lower level than that where the error is. I noticed in the tcpdump I did that the resource was sent out of order. (I still have to take the tcp seq and manually line them back up and see if the md5 matches, will do that next)

**Comment by nightshade427** [comment]
Okay using the latest libuv and all latest master code, I dont get overlap anymore under load. But, instead I get some sort of strange encoding issue.
![screenshot_2015-02-21-16-07-39](https://cloud.githubusercontent.com/assets/56510/6316198/f9abfe50-b9e3-11e4-962f-f540615b89d2.png)

**Comment by nightshade427** [comment]
This results in 1/3 of time the js working, and the other 2/3 of the time js not working (due to the encoding /char issue). See the below screenshots (first is it working, second is it experiencing the encoding/char issue).
![screenshot_2015-02-21-16-15-24](https://cloud.githubusercontent.com/assets/56510/6316228/18984818-b9e5-11e4-9c72-b3c936ef46ad.png)
![screenshot_2015-02-21-16-15-31](https://cloud.githubusercontent.com/assets/56510/6316229/1c78c656-b9e5-11e4-8391-e6a22ea6b642.png)

**Comment by nightshade427** [comment]
Any ideas on why sometimes it gives: "ut.call(".....")" which is incorrect vs "ut.call("  ")" which is correct. It only seems to do this when requesting multiple things from wookie at same time. If I just do the js file by itself it gives the correct result 100% of the time.

**Comment by nightshade427** [comment]
Nevermind it also still cuts the inputs as well like before. See attached screenshot.

![screenshot 2015-02-21 17 17 23](https://cloud.githubusercontent.com/assets/56510/6316476/986c97d0-b9ed-11e4-89e8-88d16fc78778.png)

**Comment by nightshade427** [comment]
Okay did a site with multiple js files and they are completely mixing together. So its not just 1 stream stomping on itself, its multiple streams mixing together like I originally thought :(

**Comment by nightshade427** [comment]
Okay tracked it down, if I add a sleep here all works perfectly:

```lisp
(defun write-to-uvstream (uvstream data &key start end)                                                                 
  "Util function to write data directly to a uv stream object."                                                         
  (sleep 0.05) ;;sleep added here to make it work                                                                                                         
  (do-chunk-data data *output-buffer*                                                                                   
    (lambda (buffer-c bufsize)                                                                                          
      (let ((req (uv:alloc-req :write))                                                                                 
            (buf (uv:alloc-uv-buf (static-vectors:static-vector-pointer buffer-c) bufsize)))                            
        (let ((res (uv:uv-write req uvstream buf 1 (cffi:callback streamish-write-cb))))                                
          (uv:free-uv-buf buf)                                                                                          
          (unless (zerop res)                                                                                           
            (let ((streamish (getf (deref-data-from-pointer uvstream) :streamish)))                                     
              (uv:free-req req)                                                                                         
              (error (errno-event streamish res))))                                                                     
          (attach-data-to-pointer req uvstream))))                                                                      
    :start start                                                                                                        
    :end end))
 ```

**Comment by nightshade427** [comment]
Check this one out and look for "accept: image/webp,*/*;q=0.8"
https://www.dropbox.com/s/a5tq3yg0331sp0a/bad.js?dl=0

That looks like a request "GET /assets/bg.png" inside a response for the "application.js".

**Comment by nightshade427** [comment]
Okay I finally found a good way to debug this, so found the issue and fix it locally and seems to work. Will make a pull request shortly.

**Comment by orthecreedence** [comment]
Nick, thanks a ton for tracking this down. I suspected it had something to do with buffering but wasn't completely sure. Are you by any chance running Wookie in multiple threads? Otherwise locking shouldn't be an issue.

I'll look into this code and see what I can do. Sorry for the month-long hiatus, things got really busy at work the past month and I could barely look at a screen at the end of each day, much less code =].

**Comment by nightshade427** [comment]
Not running in multi thread mode just normally :)

**Comment by orthecreedence** [comment]
This is really weird, I'm not able to reproduce at all on win or linux. Going to keep plugging away though.

**Comment by nightshade427** [comment]
I start up a wookie, and proxy a web page that has a bunch of css, js, images etc, and the file contents get crossed as shown above. This is done in a pre-route filter. If I do a buffer copy as shown in the pull request above the issue goes away. Hope that info helps you repo a little easier. If  I do a few requests especially in serial there is no issue at all. It's only when doing a bunch of parallel requests for differing files (like when proxying a webpage) that it happens. I think it's when say 10 requests come in to wookie and each request makes a carrier/drakma request for original content and those requests responses come back in chunks (some from fileA some from fileB) and those chunks each get written to the output buffer as they come and so get mixed up. If that makes sense?

**Comment by orthecreedence** [comment]
I'm doing simultaneous carrier requests (20 of them per run) for a number of JS files served by wookie and comparing the md5s of the files coming back to the known md5 sums of the files (precomputed). I haven't gotten one mismatch, after testing about 50 times.

Can you make sure you're loading fast-io from master?

**Comment by nightshade427** [comment]
So for example: proxying content with wookie. Two request come in at same time, one for js, one for css, the js wookie request makes a request for the original js file via carrier, at the same time the css wookie request makes via carrier as well (as they both are non blocking and so wookie switches bestrewn the two wookie requests). The js carrier request gets some data back, writes to buffer, then the css carrier request gets some data back and writes to buffer, then the js carrier request gets some more data and writes to output buffer (the data is now mixed) and the mixed response is send as the response from the js original js wookie request. Not sure if that helps or makes it more confusing. 

But, basically when accepting lots of requests at same time with wookie and those request themselves make async network requests the output buffer seems to get trampled.

**Comment by nightshade427** [comment]
Yeah I'm use latest master of fast-io and fast-http. 

It's not when wookie itself is serving the files. It's when wookie requests themselves make outbound async requests. 

Request 1 a.js => wookie => carrier request to get a.js from a different server. 

Request 2 b.css => wookie => carrier request to get b.css from a different server. 

Request 1 gives back result with a.js and b.css mixed together under load.

**Comment by orthecreedence** [comment]
Ah ok, thanks for describing the proxying, I didn't get that the first time.

Either way, I'm really surprised output-buffer is getting overwritten because it's only ever used synchronously. Let me do some more testing with the proxying aspect.

**Comment by nightshade427** [comment]
Try and make sure the resources you proxy have some fairly large chunked and non-chunked responses too (lots of the files I proxy arelarger and might contribute to issue). :)

**Comment by nightshade427** [comment]
Thanks again for looking into it. Let me know if I can give any more info to help you repo the issue.

**Comment by orthecreedence** [comment]
How large are we talking? I'm mostly doing <= 200K (just javascript files) but they are definitely over the 64K buffer limit (they should trigger multiple chunks/writes).

I rewrote the test to proxy back to an apache process, and getting the same result (all the MD5s are coming back fine). You're on linux/sbcl right? I'm doing linux/sbcl as well, not seeing the overlap =[. Any other details that might help?

**Comment by nightshade427** [comment]
I can bring my server my up with master wookie (not my patched version and uri you can hit) so you can see effect maybe? I'm running on Ubuntu 14.10 and sbcl 1.2.8 and latest quick lisp with master repos in local-project.

**Comment by orthecreedence** [comment]
Out of curiosity, what libuv are you using? I just upgraded to 1.4.2 in case that was the problem, can you do the same (you might have to compile from source)?

**Comment by nightshade427** [comment]
I'm using 1.4.0. I can try 1.4.2 after to take a look at the two uris above. Let me know and I will take the uris down and upgrade libuv :)

**Comment by orthecreedence** [comment]
1.4.0 is probably fine, I was on 1.0.0-rc2

**Comment by orthecreedence** [comment]
See it now =]. Had to load a 3.5mb file.

**Comment by nightshade427** [comment]
Okay great! So you don't need the test uris above anymore? Safe to take down?

**Comment by orthecreedence** [comment]
Yeah please take them down. However, I'm noticing a failure only on large files, consistently. So any 3mb file fails, whether other requests are coming through or not. Then when I curl that file through the wookie proxie, the MD5 matches.

Are you seeing this on random files or different ones per-request, or is there any kind of consistency?

**Comment by nightshade427** [comment]
It's seem to vary as you can see in the first uri above. If you full refresh a few times, each time it effects different files. If you then take a file that got mixed and ask for just that file in browser alone its perfectly fine. 

The second uri (patched) works every time perfectly.

**Comment by orthecreedence** [comment]
Ok, thanks. I'll keep working to reproduce.

**Comment by nightshade427** [comment]
Thanks let me know if I can help in any way or if you accept the pull request (in which case I will switch back to master instead of my fork).

Thanks again :)

**Comment by orthecreedence** [comment]
Ok, can you pull cl-async and wookie (both master)? I implemented your copying concept (I think copying the output buffer is the only way). Also pushing some somewhat unrelated fixes in Wookie. Oh, and cross your fingers =]

**Comment by nightshade427** [comment]
Sure thing, I will test it out tonight. Thanks!!!

**Comment by nightshade427** [comment]
This is working! Thanks :)
