### ISSUE TITLE
ssl doent work with stream:t set

### ISSUE THREAD

**Issue by nightshade427** [orthecreedence/cl-async#126]
When setting stream to "t" when calling tcp-ssl-connect cl-async fails. This is used in libraries likedrakma-async.

**Comment by orthecreedence** [comment]
Should be fixed in 939644c =]

**Comment by nightshade427** [comment]
I get ```r "/assets/application-f618bbad23dfea475988aba62d323d59.js": HTTP connection timeout: -1: HTTP stream client timed out.``` when proxying several ssl resources at the same time. I dont get this error when proxying lots of non-ssl resources.

**Comment by orthecreedence** [comment]
Is your proxy terminating SSL and requesting HTTP resources? Or is it terminating SSL then requesting other SSL resources?

**Comment by nightshade427** [comment]
It is non ssl to ssl:

http-app.js => wookie => carrier/drakma => https-app.js on another server

**Comment by nightshade427** [comment]
Actually this seems to happen on non ssl too under load.

**Comment by nightshade427** [comment]
Okay if I replace drakam async with carrier the issue goes away. I think this has to do with the newly added stream: t support added above (which is what drakma uses vs carrier).

**Comment by nightshade427** [comment]
It errors with the above ```HTTP connection timeout: -1: HTTP stream client timed out.``` with drakma. With carrier it just hangs and sits there forever waiting.

**Comment by nightshade427** [comment]
Okay I found a case that repos it every time. Going to try and see why its erroring.

**Comment by nightshade427** [comment]
It seems as though the finish-request callback isnt being called. Its like fast-http reads the data fine each time, but never triggers the finshed callback.

**Comment by nightshade427** [comment]
Let me know if you need anything else to help repo the issue.

**Comment by nightshade427** [comment]
Okay I got ssl disabled for the site above.
This works:
```lisp
(as:with-event-loop (:catch-app-errors t)                                                                      
           (bb:catcher                                                                                                  
            (bb:multiple-promise-bind (body status headers) (das:http-request "http://www.firma8.com/assets/bg.png")    
              (format t "~&status: ~s~&headers: ~s" status headers))                                                    
            (t (e) (format t "error: ~a" e))))
```
This does not:
```lisp
(as:with-event-loop (:catch-app-errors t)                                                                      
           (bb:catcher                                                                                                  
            (bb:multiple-promise-bind (body status headers) (das:http-request "https://www.firma8.com/assets/bg.png")    
              (format t "~&status: ~s~&headers: ~s" status headers))                                                    
            (t (e) (format t "error: ~a" e))))
```
The only difference is the ssl.

**Comment by nightshade427** [comment]
It also only seems to effect files of 32k or larger? When I do png's over ssl that are smaller than that they work.

**Comment by nightshade427** [comment]
Found and fixed once I saw ones under 32K worked. The size of the ssl response chunks are 16k, and the code currently called ssl-run-state twice, so if the size was larger it was never called again and data was left hanging in the stream.

Making pull request now for the fix. Will link to here for context.

**Comment by orthecreedence** [comment]
Thanks a ton for taking a look at this. Sorry I've been MIA the past week or so, had a lot of busy days/nights. Have you found this works for all larger file sizes?

**Comment by nightshade427** [comment]
All the large ones I've tried so far :)

**Comment by orthecreedence** [comment]
Perfect, thanks!
