### ISSUE TITLE
SB-SYS:MEMORY-FAULT-ERROR while calling ssl-ctx-set-options

### ISSUE THREAD

**Issue by borodust** [orthecreedence/cl-async#131]
While trying to use [Carrier](https://github.com/orthecreedence/carrier) i stumbled across the issue. After some digging I narrowed it to this:
* throws memory fault:
```lisp
(let ((ctx (ssl-ctx-new (ssl-tlsv1-client-method)))
	      (opts (logior +ssl-op-all+ (logior +ssl-op-no-sslv2+ +ssl-op-no-sslv3+))))
	  (ssl-ctx-ctrl ctx +ssl-ctrl-options+ opts (cffi:null-pointer)))
```
* seems to work fine:
```lisp
(let ((ctx (ssl-ctx-new (ssl-tlsv1-client-method)))
	      (opts (logior +ssl-op-all+ (logior +ssl-op-no-sslv2+ +ssl-op-no-sslv3+))))
	  (ssl-ctx-ctrl ctx 32 opts (cffi:null-pointer)))
```

I'm using last `cl-async` from quicklisp repo, `openssl 1.0.2.c-1` and `sbcl 1.2.12-1`.

Issue seems related to definition of `+ssl-ctrl-options+`, which is defined as
```lisp
(defconstant +ssl-ctrl-options+ 3)
```
but according to [ssl.h](http://www.opensource.apple.com/source/OpenSSL/OpenSSL-7.1/openssl/ssl/ssl.h?txt) it should be `32` instead of `3` (See definition of `SSL_CTRL_OPTIONS` there).

Did i misconfigured smth?

**Comment by orthecreedence** [comment]
Weird, I'm seeing all the ssl.h references to SSL_CTRL_OPTIONS point to 32 as the value (even on Windows). I wonder if I just mistyped it when I originally created the CFFI mappings.

I think if I get the chance in the next week or so I'll just grovel the header file, but until then I'll at least change it to 32.

Great catch, thanks for narrowing it down.

**Comment by orthecreedence** [comment]
Ok, this has been updated, can you try the master branch and see if it's fixed?

**Comment by borodust** [comment]
np, sry for being late, i'll try asap, but right now I'm a bit busy with work stuff

**Comment by borodust** [comment]
Seems to be working ok. Thanks!

**Comment by orthecreedence** [comment]
Glad it's working!
