### ISSUE TITLE
Signal-handling on Posix in general?

### ISSUE THREAD

**Issue by priyadarshan** [orthecreedence/cl-async#134]
Hi,

The manual's [Signal handling section](http://orthecreedence.github.io/cl-async/signal-handling) says,
```
Signal handling really only works on linux. It will run on windows, but don’t be surprised if your signals don’t catch.
```

Do you know if signals work on Posix in general?

We are going to start using cl-async on FreeBSD soonish, so I wanted to know, just in case we need to plan around that.

Thank you for cl-async, it is a real gem in CL landscape.

**Comment by orthecreedence** [comment]
Hey, sorry to leave you hanging. I haven't had a chance to fire up a FreeBSD vm in the past week to test, so the answer is "I don't know." My best guess is that you'll have very few problems on any BSD (including OSx), but that's just a guess =].

If I remember correctly I ran the test suite on FreeBSD after switching from libevent to libuv, but that was a while ago now. Let me know if you run into any snags, I'll try to fix them as soon as I get the time (but mainly, we're at the mercy of libuv for many things).

**Comment by priyadarshan** [comment]
Thank you, looking at FreshPorts, it seems libuv is well tracked on FreeBSD (http://www.freshports.org/devel/libuv/). I will let you know, in case. The ticket could be closed if you wish.
Thank you!

**Comment by orthecreedence** [comment]
Ok cool, I figured they would support BSD since it's a fairly well-used platform. I'll close for now, but if you notice any issues please re-open.
