### ISSUE TITLE
Unable to load libuv.dylib

### ISSUE THREAD

**Issue by JacksonGariety** [orthecreedence/cl-async#138]
When trying to install via quicklisp I immediately get:

```
> Error: Unable to load any of the alternatives:
>           ("libuv.dylib")
```

libuv is installed via homebrew in the usual location (/usr/local/Cellar/).

**Comment by PuercoPop** [comment]
Following the thread of https://github.com/orthecreedence/wookie/issues/73#issuecomment-208114841

I am unfamiliar with the best way to search for libraries, but it appears that CFFI honours the [DYLD_LIBRARY_PATH](https://github.com/cffi/cffi/blob/604b3eed40fb8ff2e064e7540a53692a0e5bdc12/src/libraries.lisp#L63) variable.

**Comment by orthecreedence** [comment]
Hey guys, sorry for the late response. I've had nothing but trouble with OSx and loading libraries. Every time I turn around it jams them somewhere new, and I don't have a Mac to test on so I really just rely on pull requests. As Javier pointed out, perhaps just doing `DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/path/to/libuv.dylib ccl ...` would do it. Other than that, please feel free to open a pull request against [cl-libuv](https://github.com/orthecreedence/cl-libuv) and just keep adding the locations in by hand. It's frustrating, but maybe at some point library maintainers will stop putting them in random ass places.

**Comment by ekuiter** [comment]
I had the same problem although libuv was correctly installed to `/usr/local/lib/libuv.dylib` with Homebrew. I used `ccl` (which defaults to `ccl32`), but brew installs libuv as a x86_64 library. After switching to `ccl64` loading cl-async works like a charm :)
(You could possibly compile libuv as a 32-bit library too and continue to use `ccl32`.)
