### ISSUE TITLE
Error running rest FS_MONITOR

### ISSUE THREAD

**Issue by DanielKeogh** [orthecreedence/cl-async#139]
As per instruction here: http://orthecreedence.github.io/cl-async/tests
This is on sbcl running on arch linux. 

Copy Pasta:

 Running test FS-MONITOR ....X
 Running test FS-WATCH-FAILURE .
 Did 129 checks.
    Pass: 128 (99%)
    Skip: 0 ( 0%)
    Fail: 1 ( 0%)

 Failure Details:

---

 FS-MONITOR []: 
      Unexpected Error: #<SIMPLE-ERROR "test timeout" {1009075893}>
test timeout..

---

**Comment by Chream** [comment]
I have the same. Also fail in ssl tests.

Ran on:
ProductName:	Mac OS X
ProductVersion:	10.11.6

```
Did 129 checks.
    Pass: 128 (99%)
    Skip: 0 ( 0%)
    Fail: 1 ( 0%)

 Failure Details:
 --------------------------------
 FS-MONITOR []: 
      Unexpected Error: #<SIMPLE-ERROR "test timeout" {1007B0A2C3}>
test timeout..
 --------------------------------


Running test suite CL-ASYNC-SSL-TEST
 Running test TCP-SSL-SIMPLE-CLIENT-SERVER X
 Did 1 check.
    Pass: 0 ( 0%)
    Skip: 0 ( 0%)
    Fail: 1 (100%)

 Failure Details:
 --------------------------------
 TCP-SSL-SIMPLE-CLIENT-SERVER [Test a simple client/server implementation over SSL]: 
      Unexpected Error: #<SB-INT:SIMPLE-PROGRAM-ERROR "odd number of &KEY arguments" {10081CEF53}>
odd number of &KEY arguments..
 --------------------------------


Running test suite CL-ASYNC-THREADING-TEST
 Running test THREADING-DELAY .
 Did 1 check.
    Pass: 1 (100%)
    Skip: 0 ( 0%)
    Fail: 0 ( 0%)

T
NIL
```

**Comment by Plisp** [comment]
From my testing on void linux, fs event support seems to be broken at the libuv level. After the first event it fails to deliver any further notifications. Can you test if this is the case on arch linux?
