### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [orthecreedence/cl-async#153]
Fantastic repo!  Are you still maintaining it?

**Comment by orthecreedence** [comment]
Not really. I accept PRs, but not actively using it in any projects at the moment. That said, it works great, and I used it in production for years. I think the only issues it would have going forward would be its dependency library, cl-libuv, keeping up with the OS-packaged versions of libuv.

If you want cross-platform async in lisp, it's certainly your best bet as far as I know.

**Comment by Bohdan-Khomtchouk** [comment]
Would you be interested in giving a talk on async in Lisp at Stanford this year?  Since you live in SF, we're practically neighbors!  I'd be delighted to host you for a departmental seminar (on either async in Lisp or any another Lisp project you're currently passionate about).

**Comment by orthecreedence** [comment]
I think I may have answered this here :) -- https://github.com/turtl/core-cl/issues/2#issuecomment-373966505

I haven't done anything in Lisp for a few years now, so I might not have much to bring to the table. Most of my projects are in limited maintenance. I really appreciate the invite though.
